(source "melpa" "http://melpa.milkbox.net/packages/")
(source gnu)
(source marmalade)
(source org)

(depends-on "auto-complete")
(depends-on "flycheck")
(depends-on "highlight-indentation")
(depends-on "indent-guide")
(depends-on "js2-mode")
(depends-on "let-alist")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "smartparens")
(depends-on "yasnippet")
